### ISSUE TITLE
Cluttered output in pintk

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1038]
The text output of `pintk` is very cluttered.  Here is a simple example output from running pintk, adding "F3 0 1" to the model and clicking Fit:

[out.txt](https://github.com/nanograv/PINT/files/6393554/out.txt)

There is lots of distracting and extraneous output. But the worst is all the INFO statements *after* the results of the model fit are printed. This often causes the useful output to be scrolled off the screen.  The last thing printed should definitely be the summary of the fitted model.  Perhaps `pintk` should suppress all INFO statements and just send them to a log file or something in case you want to inspect them (e.g. in a pane of the GUI).

**Comment by champagne-cmd** [comment]
@paulray it seems astropy's setup doesn't make this as easy as you would think. It is easy enough to suppress the astropy log output below a given level and to output to a log file. However, if you use the 'setLevel' function to suppress INFO statements, it suppresses them both to stdout and the log file. There doesn't appear to be an easy way to separate what is suppressed in the log file and what is suppressed to stdout without going in and changing astropy itself. A couple solutions I've thought of:

1. Put an option in pintk for turning INFO statements on and off, defaulting to off. So if a user wants more output they can opt for it but it doesn't clutter the screen for users that don't need it. This would still clutter the screen if turned on, and you wouldn't be able to see the INFO statements anywhere for runs with it turned off.

2. Go in and change stdout for pintk runs to redirect all output to a log file instead of the terminal. For output we do want going to the terminal, such as the fit results, the output can be switched back to the terminal temporarily. We might have to pass the original parameter into certain functions depending on its scope and where the redirection is needed, which could be a little awkward. But this solution may be more in line with what you were thinking above.

What do you think?

**Comment by paulray** [comment]
Since Option 1 seems easy and it might be sufficient, let's try that first.
