### ISSUE TITLE
Codecov is overly agressive

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1082]
We should modify how Codecov is used, so that it doesn't cause CI tests to fail just for a tiny decrease in coverage.
Perhaps the Github Action can be made to always return True so the tests always pass, but the coverage report is still available for inspection?

**Comment by aarchiba** [comment]
I think #1085 resolves this, but I think because it posts coverage reports as github comments you'll still get emails for those. (If you get emails for github comments, I think that can be turned off.) I think we could ask that it not post these comments unless there has been a coverage change - which will happen if the number of lines of source code change, or the number of covered lines, but in any case I think it'll still email basically all the time. https://docs.codecov.com/docs/pull-request-comments
