### ISSUE TITLE
Collect papers (& code?) that use PINT

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1101]
We should have a list on a PINT website (not sure which, maybe readthedocs, maybe GitHub) of which papers use PINT.  This might just be which cite the main PINT paper.

It would be even better if we could collect the scripts and data from those paper to put them in a `contrib` area.  Maybe lower the bar to allow users to contribute there without all of the various checks that go into a standard PR.

**Comment by aarchiba** [comment]
Technically the easiest way to keep such a list would be just to add a page to the docs with ADS links (and maybe author year and title), maintained by an eye on the "papers citing" entry for the PINT paper.

As for soliciting contributions, again the easiest technical thing is just have a policy that dropping scripts/notebooks into `contrib` doesn't need more than the most basic review ("Is it `rm -rf /`?") in a PR, and that people are welcome to just email a habitual PINT author to arrange inclusion if making a PR is inconvenient. We'd have to sort out what to do with what went in `contrib` - notebooks are the simplest, they could send us an executed notebook and we could just plonk it in, to be rendered as part of the docs. Scripts we can't run ourselves we'd need to rig up some plumbing so that they appeared on their own page in syntax-highlighted and downloadable form, but that's probably doable. Notebooks we could actually run would be the nicest - among other things they'd tell us when we broke something - but the barriers to that are a little higher, among other things we'd have to include the data they depend on. (Though in principle we could use Astropy's `download_file` to pull things out of DOI-based online repositories.)

**Comment by aarchiba** [comment]
Somewhat tangentially related but #942 would help make our examples much more useful.
