### ISSUE TITLE
Consider unifying zima and make_fake_toas()

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#1121]
There is a `make_fake_toas()` function in toa.py here: https://github.com/nanograv/PINT/blob/4c8aa4b682e5f07d71784828ef94267e534340a3/src/pint/toa.py#L833

It largely overlaps with code in the command line script zima. 

We should consider reducing the replication and making zima just call an enhanced version of `make_fake_toas()`

**Comment by aarchiba** [comment]
https://github.com/nanograv/PINT/blob/master/src/pint/scripts/zima.py - I'm not sure it's actually all that much more complicated, now that I come to look at it, but the things that it supports that `make_fake_toas` does not appear to be:

- Slightly randomize the observation times instead of perfectly even spacing
- Cycle through several different frequencies
- Add noise equivalent to the TOA formal uncertainties
- Use input TOAs but tweak them so the residuals are fake

**Comment by paulray** [comment]
This is now being discussed in #1122
