### ISSUE TITLE
PINT unconditionally removes any logging configuration the user may have set up

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#1243]
When the module `pint.logging` is imported anywhere, it runs `log.remove()`, discarding any logging set up by the user of this library. The loguru bug tracker contains examples where just such behaviour from a library caused problems for a user: https://github.com/Delgan/loguru/issues/534 and https://github.com/Delgan/loguru/issues/553 . The advice from the author of `loguru`, seen in the latter, is:

> Packages shouldn't touch the logger handlers, it's the user responsibility to configure them.

I realize we as PINT developers want users to have a nice experience running PINT, but what a nice experience looks like is going to be different for notebook users, script users, pintk users, and large-cluster users.

The documentation also contains

> Using the logger in your scripts is easy, and you can [configure()](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.configure) it at start. To use Loguru from inside a library, remember to never call [add()](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.add) but use [disable()](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.disable) instead so logging functions become no-op. If a developer wishes to see your library's logs, he can [enable()](https://loguru.readthedocs.io/en/stable/api/logger.html#loguru._logger.Logger.enable) it again.

I'm not sure we want to disable logging, so perhaps the author of `loguru` has a different notion of what logging is for than we do?

**Comment by dlakaplan** [comment]
This is a bit tricky, and I'd be happy to discuss further.  I did see that discussion on the loguru docs but I didn't know what the average user experience would be for PINT users.  There are a few ways I could think of to look at this:
* only remove a handler if it goes to `stderr`.  So that would presumably be the `loguru` default.  Otherwise just add a new one?
* don't add any new handlers by default, but require all users to do so (this seems the most library-like, but would lead to additional boiler-plate that would need to be used everywhere)
* only remove the handler if it is identical to the `loguru` default (not sure how to determine that)
* try to preserve any non-standard settings and pass them through

Are there specific issues/use cases that you can think of?  Other ways to solve this?

**Comment by dlakaplan** [comment]
Another possibility is that the logging is not configured by default in `__init__.py`, but instead all users would have to import `pint.logging` if they want to use this setup.  Alternatively it could just be triggered by a `pint.logging.setup()` command or similar.  Again, that's an extra step for most users, but maybe it's preferable.

**Comment by dlakaplan** [comment]
Note that we are not using the astropy logger any more - is enterprise? 

I did discuss logger choice within the cyberI group to see if we could come up with a common solution among different groups.

**Comment by dlakaplan** [comment]
See https://github.com/nanograv/PINT/pull/1232. I think this does what you are discussing, and just adds one more line. Maybe also easier to configure for the average user (e.g., to change levels).

**Comment by dlakaplan** [comment]
Should we close this now?

**Comment by scottransom** [comment]
I think so!
