### ISSUE TITLE
When I run toa.get_TOAs() , this will usually report an error

### ISSUE THREAD

**Issue by zzzlllccc** [nanograv/PINT#1250]
When I run  toa.get_TOAs() , It usually fails. I don't know why this is, if it's because I didn't do some steps correctly.

**Comment by scottransom** [comment]
Are you able to do "wget https://data.nanograv.org/static/data/ephem/de421.bsp"?  If so, please try to load the TOAs again.  Seems like it was likely a temporary network issue.  The first few times you use PINT you kind of need to be on the internet since it has to grab important files (like this JPL Solar System ephemeris).

**Comment by zzzlllccc** [comment]
Thank you very much for your reply, I tried it today and it may have been due to a network problem, this has now been resolved, thank you again
