### ISSUE TITLE
Release info on GitHub is out of date

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1263]
Not sure how/where this is defined, but:
https://github.com/nanograv/PINT/releases
only lists 0.8.3.  Should we make updating that part of the pypi/anaconda release sequence as well (@paulray)?

**Comment by paulray** [comment]
Hmm. We could either update that, or delete it. I wasn't aware of that release mechanism.

**Comment by dlakaplan** [comment]
Yes, I don't know if it's worth trying to keep 3 places synced.

**Comment by paulray** [comment]
Not sure what the value of the GitHub release channel is. You can always check out a tag to get any version you want.

**Comment by dlakaplan** [comment]
I guess it's trivial to just delete that section if we decide to do so.

**Comment by aarchiba** [comment]
I think my concern at the time was to ensure that folks working on the NANOGrav 15yr data release had a really clear idea what version they were doing because of the position change for the telescope. I think in general the section exists to help make it obvious which tags you should consider checking out? I agree that having the version in three separate places is asking for trouble, and I'm not particularly devoted to having this.

**Comment by paulray** [comment]
OK, to try it out I made a new "Release". It is indeed totally trivial to make a new one.
So, I guess I'm OK adding that to the instructions for doing a release, or just deleting the two that are now there.

**Comment by aarchiba** [comment]
Do we want to add something to the release instructions about CHANGELOG.md? I have often found myself in a situation where the CHANGELOG doesn't have a section for the current release and I don't know which of the changes in the "Unreleased" section actually have been released.

**Comment by paulray** [comment]
This should never happen. Part of making a Release is changing the "Unreleased" section to the name of the release. Everything in the Unreleased section should be from PRs merged since the last tagged release.

**Comment by aarchiba** [comment]
That instruction is not actually in the "how to make releases" part of the docs, is it?

I think what happened was that I hadn't added a CHANGELOG entry so I hadn't been warned that I needed to rebase; that rebase should sort out what goes where in the CHANGELOG.

**Comment by paulray** [comment]
Yeah the docs need a bit of clarification. I'll try to add that.

**Comment by aarchiba** [comment]
Unfortunately, merging #1257 merged its changes into the already-released part of the CHANGELOG. I've fixed that in the test cleanup PR (#1253) but this kind of thing is going to keep happening. It's not a totally unfamiliar problem - https://about.gitlab.com/blog/2018/07/03/solving-gitlabs-changelog-conflict-crisis/ - but it sure is annoying to deal with constant rebases just because of CHANGELOG entries.
