### ISSUE TITLE
Do derivatives wrt noise parameters make sense in design matrix?

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1310]
Context: I am trying to implement the fitting of noise parameters.

The designmatrix() function tries to compute derivatives w.r.t. noise parameters if they are unfrozen. Right now this throws an exception because the derivative functions are not implemented. Does this behavior make sense? 

I think the derivatives w.r.t. noise parameters should either be excluded from the design matrix or be set to zero (because timing residuals do not depend on noise parameters).

**Comment by aarchiba** [comment]
I don't think it will be possible to fit for noise parameters using PINT's Fitter framework. Those are designed to operate as least-squares fitters, that is, their goal is to produce the smallest possible scaled sum of squares of residuals. (It's a little more complicated with correlated errors but essentially the same.) If you allow them to adjust EFAC (say) they will correctly conclude that they can produce really small scaled sums of residuals by shooting EFAC through the roof. 

"Fitting" noise parameters will require some kind of statistical analysis that sets some other, appropriate goal. The Bayesian fitters we used for the 15-year data release adjusted the noise parameters so that the distribution of residuals matched the idealized distribution of residuals as well as possible. (And they used a linearized version of the timing model to speed things up.)

There might be a frequentist analogue to this, but it's not clear how to formulate it - if all you have is a heap of non-overlapping EFACs or EQUADs, you might be able to adjust them so that the reduced chi-squared of the TOAs they affect was 1, but this won't be enough if you have both EFACs and EQUADs affecting the same TOAs, or if you have ECORRs or red noise parameters. I think Bayesian is the way to go here.

**Comment by abhisrkckl** [comment]
I think the design matrix should not contain derivatives wrt noise parameters at all, since the timing residuals do not depend on them, and the derivatives of the phase or delay w.r.t. noise parameters don't make sense. I suggest putting a condition in the designmatrix(..) function to ensure that only the parameters associated with PhaseComponents and DelayComponents (and OFFSET) get designmatrix entries.

**Comment by aarchiba** [comment]
If you're going to put that sort of condition in, I suggest that it instead raise an exception - if someone has set noise parameters to be free in their model, the Fitter is going to have a serious problem with that, especially if they are not included in the design matrix. Ideally parameter objects would individually be able to specify that they are not fittable, at which point trying to set them as free would raise an immediate exception.

**Comment by abhisrkckl** [comment]
I think such an exception should be raised by the Fitter class (maybe upon construction or while calling the fit_toas function) and not by the designmatrix function. There are use cases where the designmatrix computation may be needed with some of the noise parameters set as free (frozen=False). 

For example, if I am running a Hamiltonian MCMC with PINT, I'd need the design matrix to compute the gradients, but it makes sense to set frozen=False for noise parameters because they can indeed be estimated/fitted in a Bayesian framework.

**Comment by abhisrkckl** [comment]
> What derivatives are correct to return for a noise parameter? d-chi-squared-d-parameter I think?
I think the correct derivative will be d[log-likelihood]/d[parameter], where we also differentiate the normalization factor of the likelihood function. This is more general than d[chi-squared]/d[parameter] and will reduce to d[chi-squared]/d[parameter] for model parameters (with a factor of -0.5). 

> Do we correctly compute that?
I think it is straightforward to compute these for EFAC and EQUAD using functionalities already present in PINT. I have not done the calculation for correlated noise parameters, but I think it is possible to get those derivatives.

> Can that be meaningfully included in a "design matrix" or is it best to keep that as a separate set of derivatives?
In my opinion, the design matrix should be defined as d[residual]/d[parameter], and noise parameters don't belong in the design matrix. I think derivatives functions w.r.t noise parameters should be treated differently than the derivative functions w.r.t. model parameters.

**Comment by aarchiba** [comment]
This all sounds like noise parameter derivatives should be a separate interface from the design matrix. It is possible, even likely, that it will be useful to have optimizers that can find the maximum log-likelihood value and derivatives there - that gives one a cheap quasi-Bayesian answer that can also be used to save convergence time on a Bayesian method. Whether this can fit in the framework of our existing Fitters - which are penalized nonlinear least-squares machines - is not clear. It does seem likely that Bayesian methods are going to need more information about parameters than we can cram in a par file, so it's not clear whether this hypothetical machinery should care about whether a noise parameter is flagged as frozen or free.

In the short term, I guess there are three options:

- Don't allow noise parameters to be set as free, so design matrices never include them anyway
- Make design matrices raise an exception if any noise parameter is set as free
- Make design matrices omit noise parameters and our current Fitters ignore/raise an exception when told to fit with a noise parameter free

I can imagine arguments for any of these approaches.

**Comment by abhisrkckl** [comment]
I think option 1 is too restrictive, in the sense that it excludes new Fitter methods that may be able to fit the Noise parameters. One way to make this work is to use the `deriv_func` argument in the `add_param` function, and to tell `designmatrix` to only include those parameters for which the `deriv_func` attribute is set. Right now, I think this attribute is unused.

I think option 2 is also restrictive, in that it excludes new Fitter methods that may be able to fit the Noise parameters, but will need to compute the design matrix function. For example, a Hamiltonian MCMC fitter will work this way. 

I think option 3 is the least restrictive.
