### ISSUE TITLE
tests depend on libstempo/tempo/tempo2

### ISSUE THREAD

**Issue by demorest** [nanograv/PINT#135]
Several tests (test_dd.py, test_dmx.py, test_model.py) run tempo and/or tempo2 via tempo_utils or libstempo to produce comparison data.  These should be rewritten so that the pre-calculated "correct" answer/dataset is stored in the pint tests area rather than calling tempo/tempo2 directly.  This will reduce dependency on external packages that are otherwise not needed, and make the tests independent of the details of the tempo/tempo2 installation on the test system.

**Comment by luojing1211** [comment]
I have fix this part at dev branch. But a good question is when can we close this issue? Is it right now, when we fix this issue at dev branch? or when we have this fixed in the master branch. 
This leads to a bigger question How do we keep this two branch synchronised? We don't want master branch out with dev. Maybe anything changed on master has to merged to dev immediately?

**Comment by matteobachetti** [comment]
@luojing1211 I think it is good practice to keep dev up to date with the changes in master

**Comment by demorest** [comment]
Closing since this has been fixed in dev branch.
