### ISSUE TITLE
Model components order

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#138]
Right now in pint delay_functions is a dictionary with two elements 'L1' and 'L2', where 'L1' represent the delays before we calculate binary delay and 'L2' the ones are binary delay or after that. Binary delay will take the result of  total 'L1' delay as the input. 

Issue:
- 'L1' and 'L2' are not properly named. 
- Some delays' affiliation of 'L1' and 'L2' are not clear.  

Issue update:

In the code reorganise telecon April 13th, we have discussed the model components order problem. Right now model components do not have order in the code. But practically, some components has to be applied before some others. 

We have no solution for this yet.

**Comment by demorest** [comment]
I was thinking this through some more after looking through the JUMP code in the TEMPOs.  There are actually three levels of delay:  First (this would be "L0" in the current naming scheme) would apply directly to TOAs, ie before computing the observatory position and barycentric corrections.  Then the "L1" delays which convert from observatory-frame to barycentric TOAs.  Finally "L2" which convert from barycentric to pulsar-frame TOAs, which can be used to compute rotational phase.

In TEMPO, JUMPs are L0 by default although there is a command line option (-J) that makes them L1.  I don't think anyone usually uses this.  And as I mentioned in another thread, JUMP is done as L2 in TEMPO2.  In practice for JUMP this is not a big deal because the values are generally small.

I don't know whether we want to rearrange things in PINT to include "L0" delays.  It may be tough to accomodate this in the current scheme, because the model params would need to be known to the toa class.  I think if we try to just stick this in, it would be end up being pretty kludgey.  Maybe a larger code reorganization would be needed.

**Comment by luojing1211** [comment]
I agree with the code reorganization. I am not comfortable with some code
right now. For example, the prefixed parameter building part and the model
building part. It would be nice that after our milestone, we are aiming for
a code reorganization and optimization. What do you (all the developers)
think?

-Luo Jing

**Comment by luojing1211** [comment]
Hi all, 
This is the issue relate the discussion on the telecon. I renamed it, so it fits the purpose better. Please propose your solution in this issue.

**Comment by luojing1211** [comment]
Hi All, 
For the past week I was thinking about this problem. Right now I am thinking more about the reference frame based solution. I propose to have a "location" attribution in the model component. It contains information where this component start. 
reference frame ={name: obs/geocenter/SSB/pulsar_binary_barycenter.
                 time_scale: 'utc'/'tt'/'tdb' }
So we can know where this toas should be corrected. And we can have a method say toa_corrections(from, to) , for example toa_correction(obs,ssb) which gives you the ssb toas when you have a set of observatory toa. 

At this framework the frequency reference can be taken care as well. It is one representation of request-result desgin that Scott mentioned. 

I know this is still pretty rough. I really want to hear your comments about this. There could be some case I have not take into consideration.

**Comment by luojing1211** [comment]
This issue is solved by the new style of timing model. It should be ok to close.
