### ISSUE TITLE
Implement tempo2-style predictors?

### ISSUE THREAD

**Issue by abhisrkckl** [nanograv/PINT#1383]
tempo-style polycos are already implemented in PINT. Is there any plan to implement tempo2-style predictors in PINT? 

According to http://ipta.phys.wvu.edu/ipta-2012/files/tempo2_tutorial.pdf

> TEMPO1 produced “polycos” that are specific to a given observing frequency. For compatibility with older systems, TEMPO2 can produce polycos, but we instead recommend the use of “predictors”. The two types are similar, but predictors are based on Chebyshev polynomials and are both time- and frequency-dependent.
> 
> Section 7.1 in Hobbs, Edwards & Mancheser 2006 provide more details of why a frequency-dependent prediction is necessary for high-precision observations of binary pulsars. 
> A predictor can be produced using:
> % tempo2 -f mypar.par -pred "sitename mjd1 mjd2 freq1 freq2 ntimecoeff nfreqcoeff seg_length"

**Comment by scottransom** [comment]
Any reason why the TEMPO2 style predictors are required?  Note that that paper is not correct that you need the 2D predictions for binary pulsars.  That was shown to be incorrect after that paper was published by @demorest  and others.  The old-style polycos work just fine if you use them correctly (and it turns out that people were often *not* using them correctly before that paper came out).

**Comment by abhisrkckl** [comment]
>Note that that paper is not correct that you need the 2D predictions for binary pulsars.

I was not aware of this.

**Comment by aarchiba** [comment]
I don't think tempo2 predictors are widely supported, and it's not clear to me that there's any reason PINT should support them (if every application also supports TEMPO-style polycos). Can we close this?
