### ISSUE TITLE
Add variable solar wind model

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1402]
Update `SolarWindDispersion` model to have a different amplitude every year.

**Comment by Hazboun6** [comment]
Below is a function for the solar wind dispersion that allows for a solar wind density profile of any power of 1/r^p, where r is the distance from the Sun. The function takes an impact parameter and solar angle (I called it the impact angle, because that is what made sense to me, but it is the solar elongation). This function allows you to build any of the models that are described in You, et al., 2007, which are written in Pulsar Astronomer-friendly notation in this [paper](https://iopscience.iop.org/article/10.3847/1538-4357/ac5829/pdf). You can also find a diagram that defines all of the variables in the 1/r^p function. 

https://github.com/nanograv/enterprise_extensions/blob/master/enterprise_extensions/chromatic/solar_wind.py#L279

**Comment by Hazboun6** [comment]
In case it is useful... the link below links to the same page as above, but directly to a function that allows the user to either input a set of bins or a `t_init` and `t_final` along with a number of bins in order to bin the solar wind. It does seem reasonable that a single pulsar might not need a smaller bin than 1 year, but I don't think you should hard code that in. In the paper in my first comment we showed that a PTA can definitely resolve changes for bins that are 3 months long. 

https://github.com/nanograv/enterprise_extensions/blob/master/enterprise_extensions/chromatic/solar_wind.py#L21

**Comment by mtlam** [comment]
Rather than generically every year, can we allow a piecewise-constant definition (SWX to suggest an equivalent though admittedly confusing notation)? Allowing the start and end times of the bins and then the electron density at 1 AU would be incredibly useful. I don't know if we would want to make the `p` parameter that @Hazboun6 suggested by time-dependent but at least the coefficient term `n_0(t) (r/r_0)^-p` be time-dependent over _any_ range would be really flexible.

**Comment by Hazboun6** [comment]
@mtlam The model I linked above is effectively what you mentioned for the 1/r^2 case. It would be trivial to extend it to the 1/r^p case.

**Comment by mtlam** [comment]
Oh yeah, exactly, I think we're in complete agreement. I'm just thinking about it in terms of practicality in the par file. If we were to follow the notation for DMX, then we would want at least three values: `SWX_NNNN`, `SWXR1_NNNN`, `SWXR2_NNNN`. I would also prefer it not be tied to a different amplitude every year but over arbitrary time spans (again, I think we both agree here).

**Comment by dlakaplan** [comment]
That's basically what I was planning on implementing, but I didn't know if there was an existing model to match or if just adopting the best-guess conventions like those above is ideal.

**Comment by mtlam** [comment]
Any other model I've seen requires external inputs as priors. I would personally prefer something more generic with the flexibility such that any external input can be cast into the timeseries and frozen if needed, but that way we don't have N different kinds of solar wind models built-in to the base (extensions always welcome).

**Comment by dlakaplan** [comment]
@Hazboun6 : have you calculated the analytic derivative of your general expression with respect to p?  If not I can implement the model but we won't be able to fit for p (I can also try to look at it, but it will take more time)

**Comment by Hazboun6** [comment]
@dlakaplan I have not, but I have it in Mathematica notebook, so it should be "easy" to get. Is a week timeline okay?

**Comment by dlakaplan** [comment]
sure - no worries
