### ISSUE TITLE
Would it be useful to allow explicit conversion between binary models?

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1491]
I know this isn't possible in all cases, but would convenience methods to go between them be useful?  What's the right way to do it?  I could see an `.as(model)` method in the `PulsarBinary` class and then it uses the appropriate pairs to see when/how to convert.

* DD <-> DDS is easy
* DD -> BT is easy.  Reverse requires a value for Shapiro delay (just start with defaults)?
* DDK -> DD is easy.  Reverse needs a value for KOM
* DD <-> ELL1 could check for the approximation validity.  PK parameters also get dropped?
* I'm not sure about ELL1H

We don't support them yet, but similar considerations apply to ELL1k and DDGR.  In particular DDGR -> DD is easy, but the reverse requires a choice for the PK parameters so it might not be feasible.

Is this useful for testing and comparing different models?

**Comment by dlakaplan** [comment]
Note that I have part of this implemented in #1490 but not in a comprehensive way (just goes DD <-> DDS)

**Comment by abhisrkckl** [comment]
I think there can be conversions of ELL1 <-> ELL1H and DDH <-> ELL1H subject to the approximation validity.

I think we should be careful about conversions where information is lost (e.g. DD -> BT) and conversions where external information is needed (e.g. DD -> DDK). It is not clear to me if such conversions are appropriate or not.

**Comment by dlakaplan** [comment]
Even ELL1 -> ELL1H can be complicated, since you have to pick the number of harmonics and the right approximation (H4 vs. stigma)

**Comment by abhisrkckl** [comment]
^ I agree.

**Comment by aarchiba** [comment]
One of the questions here is whether it's better to have a `.as()` or a `.from()` method - that is, does the conversion code go in the target or the source? For Python's numeric types there is a somewhat complicated system to allow either; the issue is that if one wants to implement a new model, the way to convert both to and from it most naturally goes in the class you are adding.

I should say, the brute-force approach is to generate fake data with the one model, including pulse numbers, and then fit the second model - this should give the version of the second model that provides the best approximation to the first. Explicit conversions are better, but at a minimum this is a useful way to check such conversions.

We already have a sort of conversion ELL1 -> BT, though it might only print the converted values.

**Comment by dlakaplan** [comment]
Does this table look correct for the various potential conversions and what additional info may be needed?

|  | From ELL1 | ELL1H | BT | DD | DDGR | DDK | DDS | 
| -- | -- | -- | -- | -- | -- | -- | -- | 
| To **ELL1** | x | OK | OK (check approximation) | OK (check approximation) | OK (check approximation) | OK (check approximation) | OK (check approximation) |
| **ELL1H** | OK (need to set NHARMS) | x | OK (check approximation, set NHARMS) | OK (check approximation, set NHARMS) | OK (check approximation, set NHARMS) | OK (check approximation, set NHARMS) | OK (check approximation, set NHARMS) |
| **BT** | OK | OK | x | OK | OK | OK | OK |
| **DD** | OK | OK | OK | x | OK | OK | OK |
| **DDGR** | No | No |  No | No | x | No | No |
| **DDK** |  OK (need to set KOM) | OK (need to set KOM) | OK (need to set KOM) | OK (need to set KOM) | OK (need to set KOM) | x | OK (need to set KOM) |
| **DDS** | OK | OK | OK | OK | OK | x | OK |
