### ISSUE TITLE
Implementing TCB

### ISSUE THREAD

**Issue by dcarreto** [nanograv/PINT#151]
Hi all,
Is there an easy way to implement TCB in PINT? I tried to change line 661 in _pint/toa.py_ to:

    # For these special cases, convert the times to TDB.
    # For Barycenter this will be
    # a null conversion, but for Geocenter the scale will Likely
    # be TT (if they came from a spacecraft like Fermi, RXTE or NICER)
    tdbs = [t.tcb for t in grp['mjd']]`

but when comparing the results to tempo2 i still see a periodic difference of about ~1ms.
I am using geocentered Fermi data that i phase with Tempo2 and PINT for the comparison.
Best,
David
![pintvstempo2_tcb](https://cloud.githubusercontent.com/assets/15979778/15064028/466dd648-1382-11e6-9d5b-e733d3579319.png)

**Comment by scottransom** [comment]
Right now, no.  And truthfully, I'm not sure that we have plans to even do that.  And the reason is that basically all of the astronomical calculations (except default TEMPO2 behavior) uses TDB.  What is it that is requiring you to use TCB, if I may ask?

Since we use astropy for most of our time calculations, you might want to ask the astropy developers whether they ever intend to support TCB.

**Comment by paulray** [comment]
Note that this issue is already covered in issue #37 

In my view, I think that PINT should be able to handle TCB par files.  While I think that it was a bad choice to have Tempo2 silently use TCB as the default time scale (i.e. it uses TCB if there is no UNITS keyword in the parameter file), there are some (mostly aesthetic) reasons why TCB exists.  But, there are other priorities for PINT right now, so no effort has been expended yet to make this work.

At the moment, the workaround is to convert your par files to TDB. Tempo2 has a transform plugin that can help with that.

**Comment by dcarreto** [comment]
The reason i asked is that i have a par file with TCB units that i wanted to use with PINT.
But i see now that it is rather easy to convert the par files from one unit to the other (thanks Paul for pointing me to the transform plugin).
David

**Comment by paulray** [comment]
I thought that might be the case.  I'll close this issue now, but we'll keep the other issue open because we do want to implement TCB in the future.
