### ISSUE TITLE
Generic binary model?

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1602]
Should we implement a generic binary model more like T2?  Potential behavior:
* If we see TASC/EPS1/EPS2, use ELL1 base
* If we see T0/OM/E, use DD base
* If we see M2/SINI, use that Shapiro delay version (e.g., DD)
* If we see STIGMA/H3/H4, use that Shapiro delay version (e.g., ELL1H)
* If ELL1 and OMDOT/LNEDOT, use ELL1k
* If we see SHAPMAX, use that Shapiro delay version (e.g., DDS)
* If we see MTOT/XPBDOT/XOMDOT, use DDGR
* If we see KIN/KOM, use DDK

Are there any potential clashes?  Is the logic here clear?  Is this actually desirable?  How different is this from T2?  Is there any reason to maintain BT in this?

**Comment by dlakaplan** [comment]
@scottransom

**Comment by dlakaplan** [comment]
I wonder if the wrapper class can be generic but then it will point to the specific implementation in `stand_alone_binary_models`.  Otherwise I worry the implementation would need a lot of control statements.  The alternative is duplicated code but inheritance makes that not so bad.

**Comment by abhisrkckl** [comment]
>Is there any reason to maintain BT in this?

It seems to me that BT is a proper subset of DD. I don't think we can distinguish BT and DD without the BINARY parameter if post-Keplerian parameters are absent.

**Comment by vhaasteren** [comment]
I have created PR #1695 that guesses the binary model based on the parameters in the parfile. As @abhisrkckl mentioned, sometimes there are multiple candidates. The way I have approached it is with a 'priority list':

binary_model_priority = ['Isolated', 'BT', 'ELL1', 'ELL1H', 'ELL1k', 'DDK', 'DDGR', 'DDS', 'DD']

So if multiple of these are feasible, then the first one to appear in this list is the best guess. If the only compatible model(s) is not in this list, then that one is guessed.

**Comment by aarchiba** [comment]
I'd still like to see, and am tempted to implement, a binary model based on 3d coordinates. That is, given a reasonable spec for the orbit (Keplerian parameters, possibly including derivatives, possibly computing the derivatives from GR) plus proper motion, compute a 3d position for the pulsar and its companions. Compute Shapiro delay based on the line of sight, compute the Roemer delay using a stabilised exact Earth-pulsar-minus-huge-constant formula, get the pulsar system orbital clock by root-finding, et cetera.

It would effectively end up being an independent re-implementation of pulsar timing models, with fewer/different/more explicit assumptions. Plus one could drop in 3D positions derived from differential equation solving without changing any of the rest of the (now easily testable) plumbing. 

Of course, this is a huge project, particularly for someone who is now only an amateur astronomer, so nothing should wait on this. But it is an analogue to what the T2 model was: a re-implementation with a re-assessment of all the approximations.

**Comment by vhaasteren** [comment]
That sounds pretty ambitious and awesome, @aarchiba. Question:

With 'ordinary' timing models, once more data becomes available, the timing model parameters get refined. Possibly those parameters are with respect to some epoch, like DM/Astrometry/spin parameters. How should I picture your proposal? Refinement of the model is with respect to the 3d coordinates at some epoch? Especially if you use the plural 'companions', as with an hierarchical system (?), this makes me wonder. Or would your implementation refine the model in a different way?

I'm asking because I want to understand how one would combine your timing model with other effects that could be covariant with the timing model.

**Comment by aarchiba** [comment]
The mention of companions in the plural was indeed intentional; I built my timing model for the triple system along these lines, although this is odd the one I have after working on the triple system; what I can't up with in the moment was much messier and less accurate.

The approach taken by the tempo2 developers was to expand something like this into different terms, estimate which were potentially larger than about a nanosecond, and keep all those terms. One feature of the decomposition was that many of these terms drop out entirely if you make some simplifying assumption: assume the system distance is infinite and the parallax term drops to zero, assume proper motion is zero and various other terms drop to zero.

This proposed approach does not have this feature, because it does not break the result up into terms. But you can make exactly the same assumptions and achieve the same reduction in the space of possible models. So if radial velocity is completely covariant with rescaling all frequencies, well, go ahead and freeze it. Even if it's only nearly covariant, freezing it will only hurt as much as that "nearly". More, a good model fitting tool should be able to identify parameters and parameter combinations that are nearly irrelevant, and you can decide how to handle them. (Drop in a guess at radial velocity from optical spectroscopy of the companion, say, but freeze the value for pulsar timing as that won't help constrain it.)

It's not entirely true that this wouldn't be decomposed into terms; orbital parameter derivatives are probably still usable to handle relativistic (or not) effects, and this model might easily demonstrate how they can be confused with other effects. Likewise this is somewhat orthogonal to DM modelling.
