### ISSUE TITLE
PINTk error bars do not show scaled uncertainties?

### ISSUE THREAD

**Issue by dlakaplan** [nanograv/PINT#1734]
As far as I can tell, the error bars in pintk are just `toas.get_errors()`, rather than `resids.get_data_error()` that would incorporate EFAC/EQUAD etc.  It seems like we should show the latter, at least optionally.

@scottransom ?

**Comment by scottransom** [comment]
It depends on how the EFACs/EQUADs are applied.  Because if they are in the .tim file as per the old-school way, then they get applied on TOA reading.  But if they are in the .par file, how do we know if we should apply them or not?  I suppose if we are plotting residuals for a model, then we definitely should.  But what about just plotting a histogram of TOA errors?  I don't think it should be in there for that...

**Comment by dlakaplan** [comment]
I was talking in particular about the residual plots in pintk.  The PR I put in (#1734) uses the `resids.get_data_error()` function to incorporate any scaling.  Does that make sense?

**Comment by scottransom** [comment]
Yeah, I think if there is an associated model and it has EFAC/EQUAD, then the plots should certainly show that!  So I agree.
