### ISSUE TITLE
reconsider TOA pickling

### ISSUE THREAD

**Issue by demorest** [nanograv/PINT#181]
I've recently been testing PINT more frequently which reminded me of something I've been meaning to bring up.  This is that the behavior of storing/re-using pickled TOAs by default seems kind of dangerous to me.  If/when PINT gets into more widespread use I think this will be the source of lots of confusion among users.  This is because the contents of the pickle file depend on many things:

1. The original TOA file, obviously.  We currently compare file modification times to see if the pickle needs updating.  However there are very likely situations where this breaks, for example replacing a .tim file with a previous version (ie `mv pulsar.tim.bak pulsar.tim`).  Or changing the contents of INCLUDE'd files.

2. The PINT code that was used to generate the pickle.  If some bug is fixed, or features added, in the PINT TOA-reading code, pickles need to be regenerated.  I'm surprised this hasn't bitten us more during testing (or maybe it has and we just didn't notice).  I am imagining lots of emails in the future like "I updated PINT, why didn't it fix this bug?"

3. The clock correction files.  "I updated my clock files, why didn't my timing results change?"

You probably get the idea.  We might be able to work around some of these by adding more checks, like maybe md5sums instead of file modification times, embedding a PINT version ID of some sort in the pickle, etc.  I think it would be better to just not do the pickling ever, and work on speeding up the TOA-processing code.  Or if any of you want to keep the functionality, I feel pretty strongly that it should _not_ be done by default; it should only be enabled when specifically asked for (presumably by someone who knows what they are doing and understands the risks).

Thoughts?

**Comment by scottransom** [comment]
Yeah, I like pickling.  And, in general, I think it is and will be useful for most people and for most things.  The examples that you gave that can break things are all quite rare for most users (esp once PINT becomes stable).  And we can easily handle that by having it be the first answer in the FAQ for troubleshooting (or some such -- "Have you tried re-running after deleting your .pickle file?").  It is *hugely* helpful when you have tens of thousands of TOAs because the barycentric pos/vel calculations especially are extremely expensive.

I'm not completely against making it not the default behavior, but I think that most people will actually want to use it most of the time.

**Comment by demorest** [comment]
Sorry Scott, I don't agree with pretty much any of that.  I don't think any of the situations I listed are that rare.  I think they are all likely to come up fairly regularly once we have a large user base with various workflows for how they like to process data, etc.  I know I'm finding it annoying to have to go `rm *.pickle.gz` every time I want to test some code change.  I also don't really like it when programs create files I didn't ask them to make.  I think what people want will be for PINT to run quickly so that is the problem to address.

**Comment by paulray** [comment]
I'm mostly on Paul's side on this. I've been bitten many times. I agree that pickling is useful in some cases (lots of TOAs), but making someone have to be explicit that they want that behavior is probably the best choice.

**Comment by scottransom** [comment]
As I said, I wouldn't object if it were not the default behavior.  But I do not want it removed.  I find it *very* useful and have used it a ton for Fermi photon processing (where there are lots and lots of "TOAs").

**Comment by scottransom** [comment]
Also:  "what people want will be for PINT to run quickly so that is the problem to address" is a strange statement.  Because one of the main design decisions for PINT was to break things up so that we can focus on doing only what was relevant and important at the time.  It is stupid that TEMPO/TEMPO2 re-process every TOA from scratch every time it is run.  There are zillions of repeated calculations that can be cached.  That's exactly what the pickle file does.  It allows us to bypass those calculations and focus on the "science" part -- the model fitting.  *That* is the part that we have to worry about being fast, IMO, not the things that we do (basically) once.
