### ISSUE TITLE
Issues with setup.py

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#201]
When installing a newly cloned PINT package, --inplace flag is needed for building the cython module. Without --inplace, the installed PINT package will raise str2ld module can not be found error. 
Is there a good way to fix this?

**Comment by paulray** [comment]
Surely this is just an error in how the setup.py is written. Someone must know how to make it copy that compiled module to the proper place during installation.

**Comment by luojing1211** [comment]
Another issue is the dependency of Cython. Do we require user to install Cython? Here is the numpy suggestion https://docs.scipy.org/doc/numpy/user/c-info.python-as-glue.html#cython.

**Comment by paulray** [comment]
Also, now that we have started changing the version numbers, PINT gets installed into a directory in site-packages named `pint-0.5.1-py2.7-macosx-10.11-x86_64.egg` where the version number keeps changing. Old versions don't seem to get deleted. Although `import pint` seems to automatically find the latest version, it would be good to know how to purge previous versions since they take up a lot of space with the downloaded files.

**Comment by paulray** [comment]
Also, should we include lines in setup.py like:
```
    requires = ['astropy', 'numpy', 'scipy'],
    install_requires = ['astropy>=1.2'],
```

I'm not sure all of the effects of these.  When you include them, doing an install produces stuff like this at the end of the install process:
```
Processing dependencies for pint==0.5.1
Searching for astropy==1.2
Best match: astropy 1.2
Adding astropy 1.2 to easy-install.pth file
Installing fitsinfo script to /Users/paulr/Library/Python/2.7/bin
Installing fitsheader script to /Users/paulr/Library/Python/2.7/bin
Installing fits2bitmap script to /Users/paulr/Library/Python/2.7/bin
Installing fitsdiff script to /Users/paulr/Library/Python/2.7/bin
Installing fitscheck script to /Users/paulr/Library/Python/2.7/bin
Installing volint script to /Users/paulr/Library/Python/2.7/bin
Installing wcslint script to /Users/paulr/Library/Python/2.7/bin
Installing samp_hub script to /Users/paulr/Library/Python/2.7/bin

Using /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Searching for numpy==1.11.3
Best match: numpy 1.11.3
Adding numpy 1.11.3 to easy-install.pth file

Using /opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
Finished processing dependencies for pint==0.5.1
```

**Comment by luojing1211** [comment]
That sounds a good idea. What is the potential risk of this in your mind?

**Comment by paulray** [comment]
I was thinking that if we include those requirements that setup.py might go off and install packages that the user was not expecting.

**Comment by demorest** [comment]
I can't reproduce the str2ld problem on my system.  A fresh checkout of PINT master branch, installed using "python setup.py install --prefix=$HOME" works correctly for me.  Maybe there is some issue with different setuptools/distutils versions?

**Comment by paulray** [comment]
Do you have a file `pint/str2ld.so` in your distro after that build?

If you are anywhere but in the top level of the PINT repo, it will work fine, since `import pint` gets the version you installed.  But, if you are in the top level of the repo, when you `import pint` you get the pint subdirectory of the repo as your package and that one does not have the .so file, at least in my case.

**Comment by demorest** [comment]
No, you're right, pint/str2ld.so does not exist for me.  I think the original description of the problem (above) is not accurate; the _installed_ version of PINT is actually just fine, right?  The issue is that unless --inplace is used, importing pint from the source directory does not work.  I'm not sure this is a really a problem.. if you want to import from the source dir, isn't --inplace the right option to use?

The issue with which directory gets imported when running tests is kind of annoying.  I usually cd into the tests/ subdir before running the tests, which is why they ran fine for me.  I'm not sure what is the recommended practice for python tests (ie, should they be testing the local/source dir module version or the installed module version).  Whatever the answer, getting different results based on which directory you run the script from seems kind of dangerous, would be good if there was some way around this.

**Comment by paulray** [comment]
OK, so I've deleted the build.cmd and updated README.md to explain the difference between the two methods of installing.  Any further updates and clarifications are welcome!

**Comment by paulray** [comment]
Regarding the cython issue, I see that setup.py already has some code (from @scottransom) that checks if cython is installed. If so, it builds the C code using cython. If not, it says it is using the pre-built C version. However, this must not work since the C code (`pint/cutils/str2ld_py.c`) is ignored by .gitignore. So, if we want end users to be able to build PINT without having cython installed, I think we need to remove that from .gitignore and commit str2ld_py.c to the repo.

**Comment by demorest** [comment]
The str2ld thing is such a simple little function that I think it would be cleaner to just write it directly in C and avoid cython entirely..

**Comment by demorest** [comment]
And for the standard vs inplace install, should we maybe move run-tests.sh into the tests/ subdir?  Running it from the base directory is likely to continue to cause confusion.

**Comment by paulray** [comment]
True about str2ld, but it may be nice to have the structure in PINT for adding other cython routines if we find they are necessary. Since it seems to work fine for users to not have cython installed, it should not be a problem. I removed cython from the travis build and it still passes the tests just fine. So, users should not have to worry about cython.

**Comment by paulray** [comment]
I'm not sure about moving run-test.sh.  There are at least three use cases for running the tests, that I can think of:

1. I just built PINT and I want to test it to make sure all is working before I "install" it.
2. I just installed PINT and I want to test that my installation passes all the tests
3. I'm a developer and I just changed the code and I want to test it to see that I haven't broken anything

For cases 1 and 3, it makes the most sense for the pint module imported to be the local one, and not the installed one.  For case 2, of course it must be the installed pint module.  So, what is the clean, not-too-confusing, way to support these use cases?  I'm not sure.

**Comment by paulray** [comment]
OK, I updated the Wiki and repo.

See Running Tests on the [Wiki](https://github.com/nanograv/PINT/wiki/Installation-Notes)

I separated out the pylint stuff and doc building stuff and made two run-tests scripts, one for local tests and the other for testing installed versions.  Travis now tests as if it was a user installing PINT and installs a version then tests the installed version.

I think this issue might be OK to close now.

**Comment by demorest** [comment]
Ok, sounds good!  I'm not sure I agree about keeping cython around just because we might use it in the future.  But it's probably kind of moot until I (or whoever) come up with an alternative str2ls implementation, so this is fine for now.  I may open a separate issue about str2ld to keep track of it.
