### ISSUE TITLE
Make the PINT installer automatically download and install PySPICE/cspice

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#27]
Set up auto-download of PySPICE into the PINT directory to make it as easy to install as possible and remove the need to put the absolute path the PySPICE in the setup.py

I think that @vhaasteren said he was going to look into this issue.

**Comment by vhaasteren** [comment]
Nope, I have not said that. But... it does sound like a very useful thing to have. Have PySPICE be automatically detected, and when it is not there make it install automatically.

**Comment by paulray** [comment]
Oops, sorry, I thought I recalled that from a telecon. Anyway, the suggestion can live here  until someone decides to fix it.

**Comment by demorest** [comment]
I started looking into this a while, but stopped short of implementing an auto-downloader because of a few questions this raised:

1. Although we do use PySPICE, what setup.py needs is not actually the path to PySPICE, but to SPICE itself (PySPICE typically puts a copy under its own source tree).  So to fix the setup.py issue, we could just copy PySPICE's auto-SPICE-downloader and use it to get our own copy of SPICE.

2.  It's kind of confusing how we use PySPICE for some things, but have our own cython-based SPICE wrapper for others.  I don't really remember the reason for this.  Could we possibly drop PySPICE altogether and just wrap the necessary SPICE functions directly?  Or could we get our cython functionality moved into PySPICE?  I think it would be good to have a single consistent SPICE interface.

**Comment by luojing1211** [comment]
The reason we use cython SPICE wrapper is to speed up the planets position and velocity calculation. PySPICE can not implement the vector calculation, we wrote the wrapper to avoid calling for loop in python.

**Comment by demorest** [comment]
No longer relevant since we've removed the pyspice dependence in favor of astropy/jplephem.
