### ISSUE TITLE
Have PINT able to process wideband TOAs

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#272]

**Comment by pennucci** [comment]
I guess there's no better time to try to get involved in PINT.  I will actually follow this PINT thread...!

**Comment by scottransom** [comment]
It should be able to read them already!  Processing them (properly) is a whole other kettle of fish, though...

**Comment by pennucci** [comment]
Yeah, I would think it could read them already -- at least the TOA part 
of the TOA line -- since they are formatted just like other TOAs we 
already use.  I also imagine PINT already reads/stores all of the TOA 
flags (or not?), which is where the DM info is, and therein lies the new 
stuff/kettle of fish.

**Comment by paulray** [comment]
OK, renamed issue! :-)

**Comment by paulray** [comment]
The relevant PR is #464
