### ISSUE TITLE
Python 3 error and a typo (mb.componets)

### ISSUE THREAD

**Issue by mdecesar** [nanograv/PINT#310]
I was working with David Nice and some new collaborators to get PINT working on their laptops.  One collaborator is using python 3.5, while David and I use python 2.7.

In python 2.7, mb.componets works (for example, as it is used in Timing_model_update_example.ipynb).  But it didn't work in python 3.5 -- that collaborator got an error about not having pint.model.astrometry.

Also we are assuming that it should be mb.components instead of mb.componets.  Is it easy to fix that (if it is a typo)?

**Comment by luojing1211** [comment]
It is a typo. Sorry for that. Sent from Mail Master
            On 06/13/2017 22:44, mdecesar wrote:I was working with David Nice and some new collaborators to get PINT working on their laptops.  One collaborator is using python 3.5, while David and I use python 2.7.
In python 2.7, mb.componets works (for example, as it is used in Timing_model_update_example.ipynb).  But it didn't work in python 3.5 -- that collaborator got an error about not having pint.model.astrometry.
Also we are assuming that it should be mb.components instead of mb.componets.  Is it easy to fix that (if it is a typo)?

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/nanograv/PINT","title":"nanograv/PINT","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/nanograv/PINT"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Python 3 error and a typo (mb.componets) (#310)"}],"action":{"name":"View Issue","url":"https://github.com/nanograv/PINT/issues/310"}}}

**Comment by mdecesar** [comment]
Oh no problem, thanks.

Regardless of the typo, I wanted to let you know that the command didn't work in Python 3.  When our collaborator typed "mb.componets" in the python notebook, she just got errors about not having pint.models.astropy.  I've asked her to send me the exact error (forgot to write it down during the meeting), so I'll pass that along when she sends it.

**Comment by paulray** [comment]
@mdecesar if there is still any issue here, let us know. At the moment our tests all seem to work on Python 3.5 and 3.6, so I'm closing this. We can re-open if there is a pending issue.
