### ISSUE TITLE
Possible enhancement: adding the cosine-test for testing periodicity

### ISSUE THREAD

**Issue by msjacob** [nanograv/PINT#361]
Hello,

I am working for CTA (https://www.cta-observatory.org/), an observatory of very high energy gamma-rays. We are working on a candidate for the CTA Science Tools which is gammapy (http://gammapy.org/), a python package associated to astropy and numpy.

In PINT, there are already statistical tests on periodicity like the H-test (https://github.com/nanograv/PINT/blob/master/pint/eventstats.py). There could be another interesting statistical tool for testing periodicity.

It is the cosine-test, a powerful test developed in 1994 by O. C. De Jager in his paper "On periodicity tests and flux limit calculations for gamma-ray pulsars". It was developed for gamma pulsars and is especially useful in the context of sparse data at very high energy.
It is particularly powerful for single peaked phasograms, for which we have in advance an idea of the position and width of the peak. It provides a way to test the presence of a signal located at a given phase phi_0 and for a given harmonic m.

Do you think it would be useful to have this test included in PINT ? Within the gammapy project, we tend to think that it would be more relevant to add this test to PINT than to gammapy because the cosine-test is in principle suitable for any wavelength.
If you think that such a test is interesting for PINT, I could provide a python implementation for it.

Best regards,
Marion Spir-Jacob (APC laboratory, CNRS, France)

**Comment by paulray** [comment]
I'd be interested in @kerrm's take on this

**Comment by kerrm** [comment]
It sounds like a Z^2 test with only odd phases, which would be appropriate if you knew the peak would occur at phase 0 (or shifted your data so that would be the case) and was approximately symmetric.  You'd win in this case since your chi^2 distribution would have fewer degrees of freedom.

I'm not sure how practical it would be.  If ones has a good idea of what the peak should look like, it might be better to fit a model light curve and then do a null test.  But it would be a one-line modification to the existing Z^2_m routine, so pretty easy to implement.

**Comment by paulray** [comment]
This is now merged as the `cosm()` function in event_stats.py, so I'm closing this.
