### ISSUE TITLE
GLS fitter does not update the chi2 value in the residual class

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#375]
Since GLSfitter computes the chi2 value from scipy Cholesky factorization. The Chi2 value is not updated from by the fitter.

**Comment by aarchiba** [comment]
The value returned by GLSFitter is not actually the chi-squared of the new model, it is based on a linearized estimate (this is why we need multiple iterations of GLSFitter). It is worth double-checking that Fitters let the residuals object know that the model parameters have changed, so that chi2 is recomputed. (See also PR #501 for correct lazy chi2 computation.)

**Comment by aarchiba** [comment]
Closed by #501
