### ISSUE TITLE
Python 2 Sunset

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#514]
Does this mean we should remove 2.7 from the Travis tests on January 1?
https://www.python.org/doc/sunset-python-2/

(Note, I know we don't *have* to, but it makes sense with Python 2 sunset to allow devs to use python features and packages that don't support Python 2 without causing test failures)

**Comment by aarchiba** [comment]
I would love to drop python 2 support - it also forces us to work with very old versions of packages like astropy and sphinx. Not to mention all that new stuff was added because it's nice to use. But I know of three obstacles off the top of my head:

- PRESTO's python interface is Python 2 only. This means if you want access to the contents of pfd files, fftfit, or a variety of other useful pulsar things, you're stuck on Python 2. The sunset is a good reason for *PRESTO* to upgrade but as it's a pain to install users are going to stick with the Python 2 version for as long as they can get away with it.
- PSRCHIVE is, as far as I can tell, Python 2 only. Also a pain to install. At least here the upgrade should be fairly straightforward, as SWIG generates the wrapper code and SWIG is capable of generating Python 3 wrappers. It's also possible someone could use pybind11 to write modern bindings that let you (say) actually modify PSRCHIVE files. But access to pulsar data is an important reason some users are stuck on Python 2.
- Observatories and in particular live observing machines are (rightly) quite conservative about software upgrades. Dropping Python 2 support probably means, for example, dropping the ability to use PINT to generate polycos for an observing run.

**Comment by scottransom** [comment]
Note that I am going to be working hard on the PRESTO Py3 branch(es) over the next couple weeks and hope to make a major PRESTO release when I'm happy with it.  So PRESTO should be good-to-go soon.  And I agree that because of the Swig bindings for PSRCHIVE, getting that to at least work with Py3 should be fairly straightforward.

**Comment by aarchiba** [comment]
> Note that I am going to be working hard on the PRESTO Py3 branch(es) over the next couple weeks and hope to make a major PRESTO release when I'm happy with it. So PRESTO should be good-to-go soon. And I agree that because of the Swig bindings for PSRCHIVE, getting that to at least work with Py3 should be fairly straightforward.

That's great news!

Any chance, while you're at it, that you could make PRESTO installable through conda? The entire Fermi toolchain is now distributed that way, along with lots of scientific packages.

**Comment by demorest** [comment]
I made a conda-based install of presto a while back, this works for me locally but I ran into lots of headaches with PGPLOT/gfortran and couldn't use the PGPLOT available on conda-forge.  I can take another look at this, maybe the publicly available conda packages have improved since then.

**Comment by paulray** [comment]
Closing this since we now know we are dropping Python2 as soon as we tag 0.7.
@demorest did you ever look back at presto in conda? Did you try it with conda-forge? That is where I did pint.

**Comment by demorest** [comment]
@paulray yes I did get presto working in conda, with both python 2 and 3.  I had to send some fixes in to the conda-forge PGPLOT package to enable this, those were merged a while ago.  presto itself is not in conda-forge but it's online in my anaconda.org channel (https://anaconda.org/demorest).  If @sransom thinks it's a good idea I could work on moving it over to conda-forge, but this is of course getting a bit off-topic for this issue, maybe I'll open a presto issue about it for further discussion.

**Comment by demorest** [comment]
PS same goes for a number of other pulsar packages I've conda-fied recently (psrchive, dspsr, tempo, tempo2, ...)

**Comment by paulray** [comment]
Wow, @demorest that is great!  That should be publicized more!  A lot of people would save a lot of agony if they could "conda install presto psrchive pint-pulsar tempo tempo2 dspsr" !!

**Comment by sguillot** [comment]
I will definitely try that!
