### ISSUE TITLE
How do we handle IERS_B for current (or future) TOAs

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#556]
As of now (2019 Oct 15), the file `http://hpiers.obspm.fr/iers/eop/eopc04/eopc04_IAU2000.62-now` ends on 2019 Sep 15.  If I run PINT on my data, I get this exception:
```
  File "/Users/paulr/env/pint/lib/python3.6/site-packages/pint/erfautils.py", line 28, in get_iers_b_up_to_date
    raise ValueError("IERS B data not yet available for MJD {}".format(mjd))
ValueError: IERS B data not yet available for MJD 58769.70234516895
```
So, how should we handle current or future (e.g. fake) TOAs?  The quantities in the IERS_B table are need for any `TopoObs` to compute the position and velocity at a given time. Is there an extrapolated product we could use?

**Comment by luojing1211** [comment]
This could be an astropy issue? Maybe we should make an issue on astropy.

-Jing

**Comment by paulray** [comment]
No, this doesn't seem to have anything to do with astropy.  This is all in erfautils.py.

**Comment by luojing1211** [comment]
It looks like the IERS A table is a solution. It updates daily and provides the prediction for the next year. 
see : https://astroplan.readthedocs.io/en/latest/faq/iers.html and https://www.iers.org/IERS/EN/Publications/Bulletins/bulletins.html

**Comment by aarchiba** [comment]
Currently we use only IERS B values, because they are at least in principle
final. The code should download the most recent IERS B table whenever you
supply data more recent than is available, but B does not contain
predictions and is only issued about once a month. So if you have really
recent data, we don't yet have a very good answer for you.

Also, not all of PINT uses this recent table; certain conversions are not
readily under our control and may use a different table.

Anne

**Comment by aarchiba** [comment]
The IERS A table includes values predicted by a month or two; it could be used. There will also be circumstances where people want to do calculations going forward for which there might not even be predicted values, or observatory clock corrections. Obviously in such a situation one should not expect microsecond accuracy but it is useful to be able to use it at all. We can and do emit warnings but we already emit so many warnings in ordinary circumstances that users just ignore them; they are ineffective.

Let me suggest that it be possible to set flags on TOAs, Model, and Residual objects to indicate that the results contain extrapolated or otherwise approximate answers. These would then be included in outputs of things like par files or nicely-formatted timing tables, so that no one could accidentally use extrapolated values in precision work.

**Comment by luojing1211** [comment]
Just got confirmation from @mhvk, Astropy get_gcrs_posvel() uses IERS A table, and we have a function in the erfautils, "astropy_gcrs_posvel_from_itrf()".  We can have a switch to allow the near future IERS A interpolation.  
```
from astropy.time import Time
from astropy.coordinates import EarthLocation

el = EarthLocation.of_site('Keck')
el.get_gcrs_posvel(Time('2023-01-01'))

# Downloading ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all
# WARNING: Tried to get polar motions for times after IERS data is valid. Defaulting to polar motion from the 50-yr mean for those. This may affect precision at the 10s of arcsec level [astropy.coordinates.builtin_frames.utils]
```
