### ISSUE TITLE
Add a GUI for PINT

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#57]
PINT would benefit from a GUI that has the functionality of the plk plugin for Tempo2.
It will surely add some more dependencies, so it should not be required for any basic PINT operations.

**Comment by scottransom** [comment]
qtip is the obvious choice right now
https://github.com/vhaasteren/qtip

**Comment by vhaasteren** [comment]
Yes, I just started working on this again. Do we want to have this included as part of the PINT release? It would make sense to have a gui like that included. Or are there good reasons to keep it as a separate package?

The current aim of his version has been to really emulate the plk plugin. Much remains to be done to get it feature-complete, but an initial release can be made in a few weeks of occasional coding.

The dependencies are not bad:

Currently, the dependencies are:
numpy
pyqt
Cython>=0.18
libstempo/PINT
scipy
matplotlib
ipython>=1.1
pygments
pyzmq>=2.1.11
jdcal
pyephem

I guess I can use astropy functions instead of jdcal and pyephem. Only real problem is pyqt. That can be a little bit of a pain...

**Comment by paulray** [comment]
MacPorts has two versions of pyqt.  Do you use pyqt3 or pyqt4?

**Comment by vhaasteren** [comment]
It's pyqt4

**Comment by paulray** [comment]
@vhaasteren why is this required for the NANOGrav 9yr Dataset milestone?  I don't see it as critical path for that.

**Comment by vhaasteren** [comment]
You are right. We can remove this for the milestone

**Comment by paulray** [comment]
At the last telecon, I think that @kstovall said he was going to work on this.

**Comment by cdeil** [comment]
Just in case you haven't seen this yet: JupyterLab might be an option worth considering for you if want a GUI: http://jupyterlab.readthedocs.io/en/latest/

**Comment by scottransom** [comment]
Huh...  That's pretty interesting looking, @cdeil
