### ISSUE TITLE
pintk fitting crashes

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#576]
@clp3ef when I run a fit in pintk, it crashes, like this:
```
% pintk test.par nicer.tim
INFO: This should show up [pint.pintk.plk]
INFO: This should also show up. test click revert, turn params on and off, and prefit model [pint.pintk.plk]
STARTING LOADING OF PULSAR test.par
INFO: TZRFRQ was 0.0 or None. Setting to infinite frequency. [pint.models.absolute_phase]
INFO: No pulse numbers found in the TOAs [pint.toa]
INFO: Applying clock corrections (include_GPS = True, include_BIPM = True. [pint.toa]
INFO: Special observatory location. No clock corrections applied. [pint.observatory.special_locations]
INFO: Computing TDB columns. [pint.toa]
INFO: Computing positions and velocities of observatories and Earth (planets = True), using DE421 ephemeris [pint.toa]
INFO: No jump flags to process [pint.models.timing_model]
prefit_model.as_parfile():
PSR                            J0218+4232
EPHEM                               DE421
RAJ                      2:18:06.34982150 0 0.00017573751731997185
DECJ                    42:32:17.44034000 0 0.00346490481007217209
PMRA                    5.193715886805161 0 0.09468159471800781
PMDEC                  -3.606784930806858 0 0.16883363430405207
PX                                    0.0
POSEPOCH           49150.6100000000000001
F0                   430.4610684681663828 0 6.004906042e-11
F1              -1.434149829249692884e-14 0 9.204344533056223848e-20
PEPOCH             49150.6099999999999990
PLANET_SHAPIRO                          N
DM                   61.23711333587018983 0 0.00062796490579368513
DM1                                   0.0
DMEPOCH            49150.6100000000000001
BINARY ELL1
PB                   2.028846084548673094 0 1.6160623722e-10
A1                     1.9844349671356907 0 2.8616433195144e-07
TASC               49148.5799766280722310
EPS1             5.469309955796064652e-06
EPS2            5.0963821787951832266e-06
NE_SW                                 4.0
SWM                                   0.0
TZRMJD             57982.4426975266721065
TZRSITE                                 @
TZRFRQ                                inf

Number of TOAs:  213
Number of commands:  1
Number of observatories:  1 ['barycenter']
MJD span:  57930.679 to 58438.817
barycenter TOAs (213):
  Min error:     12 us
  Max error:     164 us
  Mean error:    48.3 us
  Median error:  39.4 us
  Error stddev:  29.1 us

RMS PINT residuals are 96.436 us

/Software/lib/python3.6/site-packages/pint/pintk/plk.py:652: MatplotlibDeprecationWarning: Support for passing a (n, 1)-shaped error array to errorbar() is deprecated since Matplotlib 3.1 and will be removed in 3.3; pass a 1D array instead.
  color=color,
INFO: F0 set to 1 [pint.pintk.plk]
INFO: F1 set to 1 [pint.pintk.plk]
Pre-Fit Chi2:		466.3987 us^2
Pre-Fit Weighted RMS:	1.4797518 us
Post-Fit Chi2:		457.91202 us^2
Post-Fit Weighted RMS:	1.466227 us
          Parameter                   Pre-Fit	                Post-Fit	     Uncertainty        Difference          Diff/Unc
------------------------------------------------------------------------------------------------------------------------------------
      F0         Hz      430.4610684681663828	    430.4610684912097516	   1.0212744e-08     2.3043369e-08         383.74237
      F1     Hz / s  -1.434149829249692884e-14	-1.4371190659537939373e-14	   1.3087516e-17    -2.9692367e-17        -322.59078
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Software/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/Software/lib/python3.6/site-packages/pint/pintk/plk.py", line 340, in fit
    self.fit_callback()
  File "/Software/lib/python3.6/site-packages/pint/pintk/plk.py", line 520, in fit
    self.psr.fit(self.selected)
  File "/Software/lib/python3.6/site-packages/pint/pintk/pulsar.py", line 537, in fit
    iter=10,
  File "/Software/lib/python3.6/site-packages/pint/random_models.py", line 56, in random_models
    mean_vector *= fac
TypeError: unsupported operand type(s) for *: 'odict_values' and 'float'
```

Any idea why?

**Comment by clp3ef** [comment]
Yes, it’s a problem with switching from python 2 to 3 I think.
OrderedDict.values() no longer registers as an array that can be multiplied
by a scalar. I’ve gotten around it by replacing the line mean_vector *=
fac by mean_vector = np.array(list(mean_vector)) * fac in my local
repository.
I'm not sure why, but when I tried to convert it straight to a numpy array,
it gave me an error. There's likely a cleaner way to do this, but this
seems to work as a quick fix.

Sorry for taking so long to reply!

Camryn

On Nov 1, 2019, at 5:31 PM, Paul Ray <notifications@github.com> wrote:

@clp3ef <https://github.com/clp3ef> when I run a fit in pintk, it crashes,
like this:

% pintk test.par nicer.tim
INFO: This should show up [pint.pintk.plk]
INFO: This should also show up. test click revert, turn params on and
off, and prefit model [pint.pintk.plk]
STARTING LOADING OF PULSAR test.par
INFO: TZRFRQ was 0.0 or None. Setting to infinite frequency.
[pint.models.absolute_phase]
INFO: No pulse numbers found in the TOAs [pint.toa]
INFO: Applying clock corrections (include_GPS = True, include_BIPM =
True. [pint.toa]
INFO: Special observatory location. No clock corrections applied.
[pint.observatory.special_locations]
INFO: Computing TDB columns. [pint.toa]
INFO: Computing positions and velocities of observatories and Earth
(planets = True), using DE421 ephemeris [pint.toa]
INFO: No jump flags to process [pint.models.timing_model]
prefit_model.as_parfile():
PSR                            J0218+4232
EPHEM                               DE421
RAJ                      2:18:06.34982150 0 0.00017573751731997185
DECJ                    42:32:17.44034000 0 0.00346490481007217209
PMRA                    5.193715886805161 0 0.09468159471800781
PMDEC                  -3.606784930806858 0 0.16883363430405207
PX                                    0.0
POSEPOCH           49150.6100000000000001
F0                   430.4610684681663828 0 6.004906042e-11
F1              -1.434149829249692884e-14 0 9.204344533056223848e-20
PEPOCH             49150.6099999999999990
PLANET_SHAPIRO                          N
DM                   61.23711333587018983 0 0.00062796490579368513
DM1                                   0.0
DMEPOCH            49150.6100000000000001
BINARY ELL1
PB                   2.028846084548673094 0 1.6160623722e-10
A1                     1.9844349671356907 0 2.8616433195144e-07
TASC               49148.5799766280722310
EPS1             5.469309955796064652e-06
EPS2            5.0963821787951832266e-06
NE_SW                                 4.0
SWM                                   0.0
TZRMJD             57982.4426975266721065
TZRSITE                                 @
TZRFRQ                                inf

Number of TOAs:  213
Number of commands:  1
Number of observatories:  1 ['barycenter']
MJD span:  57930.679 to 58438.817
barycenter TOAs (213):
  Min error:     12 us
  Max error:     164 us
  Mean error:    48.3 us
  Median error:  39.4 us
  Error stddev:  29.1 us

RMS PINT residuals are 96.436 us

/Software/lib/python3.6/site-packages/pint/pintk/plk.py:652:
MatplotlibDeprecationWarning: Support for passing a (n, 1)-shaped
error array to errorbar() is deprecated since Matplotlib 3.1 and will
be removed in 3.3; pass a 1D array instead.
  color=color,
INFO: F0 set to 1 [pint.pintk.plk]
INFO: F1 set to 1 [pint.pintk.plk]
Pre-Fit Chi2:		466.3987 us^2
Pre-Fit Weighted RMS:	1.4797518 us
Post-Fit Chi2:		457.91202 us^2
Post-Fit Weighted RMS:	1.466227 us
          Parameter                   Pre-Fit	
Post-Fit	     Uncertainty        Difference          Diff/Unc
------------------------------------------------------------------------------------------------------------------------------------
      F0         Hz      430.4610684681663828	
430.4610684912097516	   1.0212744e-08     2.3043369e-08
383.74237
      F1     Hz / s
-1.434149829249692884e-14	-1.4371190659537939373e-14	   1.3087516e-17
  -2.9692367e-17        -322.59078
Exception in Tkinter callback
Traceback (most recent call last):
  File "/Software/lib/python3.6/tkinter/__init__.py", line 1702, in __call__
    return self.func(*args)
  File "/Software/lib/python3.6/site-packages/pint/pintk/plk.py", line
340, in fit
    self.fit_callback()
  File "/Software/lib/python3.6/site-packages/pint/pintk/plk.py", line
520, in fit
    self.psr.fit(self.selected)
  File "/Software/lib/python3.6/site-packages/pint/pintk/pulsar.py",
line 537, in fit
    iter=10,
  File "/Software/lib/python3.6/site-packages/pint/random_models.py",
line 56, in random_models
    mean_vector *= fac
TypeError: unsupported operand type(s) for *: 'odict_values' and 'float'

Any idea why?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/nanograv/PINT/issues/576?email_source=notifications&email_token=AMGDXVMOFUR3LD5M2FARAOTQRSNZLA5CNFSM4JIAHEZKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HWG7N6Q>,
or unsubscribe

**Comment by paulray** [comment]
Great, thanks for the fix!  Is there a reason you didn't make a PR?  I can do it if that is easier.

I think you can't make an array directly because a dict can hold a heterogeneous set of things and the .values() function returns some kind of strange class.  Converting to list() does the trick!

**Comment by matteobachetti** [comment]
Just had this problem. I need pintk for a tutorial on Thrusday. Do you think it feasible to fix it on this timescale?

Matteo

**Comment by clp3ef** [comment]
Glad I could help! Short answer: I forgot. Long answer: I made a few other small changes to my local version of random_models for new code I’m writing. I wasn’t sure if I was going to keep those changes, so I got in my head that I shouldn’t do a PR until I decided whether those small changes were staying, completely forgetting that there was a bug fix in with those edits! 

I’ll do a pull request today with that fix and maybe a few others. Thanks for the help!

**Comment by clp3ef** [comment]
Just did a pull request with the fix (#577). That looks like the only fatal error in pintk that I could find, but if you run into any issues or have any questions @matteobachetti, feel free to email me. I'm glad to see pintk getting some use!

**Comment by matteobachetti** [comment]
*some* use? It's awesome and I've used it a lot already, and spread the word among my students. Thanks for your work!

**Comment by clp3ef** [comment]
Oh, wow! Sorry I didn’t see this earlier, that’s great that it’s actually helpful! Thank you so much!

**Comment by matteobachetti** [comment]
New problem: parameter files with no TZRMJD crash pintk during fit. 

```
  File "/Users/meo/anaconda3/envs/py3/lib/python3.7/site-packages/matplotlib/cbook/__init__.py", line 216, in process
    func(*args, **kwargs)
  File "/Users/meo/anaconda3/envs/py3/lib/python3.7/site-packages/pint-0.5.4+435.gc9f7730.dirty-py3.7.egg/pint/pintk/plk.py", line 1054, in canvasKeyEvent
    self.fit()
  File "/Users/meo/anaconda3/envs/py3/lib/python3.7/site-packages/pint-0.5.4+435.gc9f7730.dirty-py3.7.egg/pint/pintk/plk.py", line 520, in fit
    self.psr.fit(self.selected)
  File "/Users/meo/anaconda3/envs/py3/lib/python3.7/site-packages/pint-0.5.4+435.gc9f7730.dirty-py3.7.egg/pint/pintk/pulsar.py", line 537, in fit
    iter=10,
  File "/Users/meo/anaconda3/envs/py3/lib/python3.7/site-packages/pint-0.5.4+435.gc9f7730.dirty-py3.7.egg/pint/random_models.py", line 84, in random_models
    rs = mrand.phase(x, abs_phase=True) - fitter.model.phase(x, abs_phase=True)
  File "/Users/meo/anaconda3/envs/py3/lib/python3.7/site-packages/pint-0.5.4+435.gc9f7730.dirty-py3.7.egg/pint/models/timing_model.py", line 580, in phase
    toas
  File "/Users/meo/anaconda3/envs/py3/lib/python3.7/site-packages/pint-0.5.4+435.gc9f7730.dirty-py3.7.egg/pint/models/absolute_phase.py", line 89, in make_TZR_toa
    PEPOCH = self.PEPOCH.quantity.value
  File "/Users/meo/anaconda3/envs/py3/lib/python3.7/site-packages/pint-0.5.4+435.gc9f7730.dirty-py3.7.egg/pint/models/timing_model.py", line 1117, in __getattr__
    % (self.__class__.__name__, name)
AttributeError: 'AbsPhase' object has no attribute 'PEPOCH'.

```

pintempo works well with the same files

**Comment by clp3ef** [comment]
Yes, this is a problem we’re running into in several places. It seems like something got switched around in model builder and now several functions that expect Timing Model Components to have access to higher up parameters (PEPOCH, FO, etc.) are unable to access those values. The issue (#574) I raised  is the same problem when adding JUMPs parameters in script. 
I got around the TZRMJD thing by adding TZRMJD, TZRSITE, and TZRFRQ into the parfile manually, assuming that TZRMJD is the mjd of the first toa after PEPOCH. If there’s no PEPOCH, I just set it to something near the middle of the data. I don’t know how to fix the bigger problem, since it’s in the model builder (or maybe timing model) code, which I’m not extremely familiar with. 

If I’m remembering wrong and adding the TZR info manually doesn’t work, just tell me and I’ll figure out a way around it. Although I’ll be in lab from 2-6, so I might not get back to you for a few hours.

**Comment by paulray** [comment]
I'm wondering why there is an AbsPhase component at all if there are no TZR parameters?

**Comment by paulray** [comment]
At least when I load a par file with no TZR parameters, I get no AbsPhase component.

**Comment by paulray** [comment]
Also, if I grab a component, I do seem to be able to see higher level parameters:
```
In [4]: m2 = pint.models.get_model('test.par')                                                                                              

In [5]: m2.components                                                                                                                       
Out[5]: 
{'AstrometryEquatorial': AstrometryEquatorial(
     MJDParameter(   POSEPOCH        53750.0000000000000000 (d) frozen=True),
     floatParameter( PX              0.0               (mas) frozen=True),
     AngleParameter( RAJ             17:48:52.75000000 (hourangle) +/- 0h00m00s frozen=False),
     AngleParameter( DECJ            -20:21:29.00000000 (deg) +/- 0d00m00s frozen=False),
     floatParameter( PMRA            0.0               (mas / yr) frozen=True),
     floatParameter( PMDEC           0.0               (mas / yr) frozen=True)),
 'SolarSystemShapiro': SolarSystemShapiro(
     boolParameter(  PLANET_SHAPIRO  N                 frozen=True)),
 'DispersionDM': DispersionDM(
     floatParameter( DM              223.9             (pc / cm3) +/- 0.03 pc / cm3 frozen=False),
     floatParameter( DM1             0.0               (pc / (cm3 yr)) frozen=True),
     MJDParameter(   DMEPOCH         UNSET),
 'SolarWindDispersion': SolarWindDispersion(
     floatParameter( NE_SW           0.0               (1 / cm3) frozen=True),
     floatParameter( SWM             0.0               () frozen=True)),
 'Spindown': Spindown(
     floatParameter( F0              61.485476554      (Hz) +/- 1e-11 Hz frozen=False),
     floatParameter( F1              -1.181e-15        (Hz / s) +/- 1e-19 Hz / s frozen=False),
     MJDParameter(   PEPOCH          53750.0000000000000000 (d) frozen=True))}

In [8]: cc = m2.components['AstrometryEquatorial']                                                                                          

In [11]: cc.RAJ                                                                                                                             
Out[11]: AngleParameter( RAJ             17:48:52.75000000 (hourangle) +/- 0h00m00s frozen=False)

In [12]: cc.F0                                                                                                                              
Out[12]: floatParameter( F0              61.485476554      (Hz) +/- 1e-11 Hz frozen=False)

In [13]: cc.PEPOCH                                                                                                                          
Out[13]: MJDParameter(   PEPOCH          53750.0000000000000000 (d) frozen=True)

```

**Comment by clp3ef** [comment]
I added the function make_TZRMJD() to absolute_phase.py to calculate the TZRMJD from PEPOCH if it doesn’t exist. That is only called on if one tries to compute residuals with abs_phase = True, which pintk does in many places, which is where it is breaking when it tries to make an AbsPhase component and can’t get PEPOCH. 
At least I think that’s what’s happening, I’m working from memory rather than the code since I don’t have the code in front of me right now.

**Comment by paulray** [comment]
Ah, I see!  On line 578 of timing_model.py it *adds* an AbsPhase component if it is not there.  This added component seems like it must not get initialized the same way as the others, so it can't access parameters from another component.  @aarchiba and @luojing1211 do you understand this? We definitely need to have a way to add components to a model in a way that makes them just like components that were made when the model object was created.

**Comment by clp3ef** [comment]
Huh. Okay, maybe I don’t understand what the problem is then, or maybe things are slightly different in the code? The error seems to pop up specifically when adding a new component to a model, maybe it’s specific to that component adding process?

**Comment by aarchiba** [comment]
The process of adding new components to models is mysterious and complicated and I have no real idea how it is supposed to work. I suspect that some but not all of the processing happens at the time of construction but I never did figure out the correct way to use that code. It desperately needs simplification. But this PR reveals:

- pintk is not being tested at all by the test suite. Running GUI applications as part of the test suite is going to be awful. So can pintk's fitting routines be run from a script? They would be much more useful if they could be. 

- The process of constructing and manipulating models is also not being tested, apart from the single case of constructing a model from scratch from a par file. A good series of unit tests - tests that focus narrowly on constructing and manipulating model objects, with no fitting or TOA manipulation or even (ideally) par file reading - would not just reveal bugs in the code but attempting to write such tests would reveal limitations and awkwardnesses in the routines we provide for working with model objects. (Parameter objects are dying for such a test suite as well.) If their interface is so awkward that unit tests cannot be written, it is probably also so awkward that people cannot do what they want to with PINT. For example, it should not be necessary to create a new par file and read it in in order to carry out an F test.

**Comment by matteobachetti** [comment]
@aarchiba, re. interface tests: actually, adding tests to the interface might not be as difficult as it seems. It should be possible to fake the signal sent to the interface and test that the proper operation is executed.

E.g. https://github.com/discos/srt-single-dish-tools/blob/master/srttools/tests/test_interactive.py

**Comment by clp3ef** [comment]
@scottransom  and I figured out what the problem is with adding components to the model. When a component is added to a model, the attribute _parent of the component isn't getting properly set, meaning it can't access parameters outside of its own component. This doesn't affect components added to the model in the initial model_builder, which is why your examples worked @paulray. Below is some code that shows the difference between adding a parameter to an existing component and adding a parameter and component at the same time. The new component has to be setup() and then have _parent manually set.

Scott and I think being able to run setup_components() more than once would fix the issue, since the setup() and setting _parent happen automatically in that process. 

```
import pint.toa
import pint.models
import pint.fitter
import pint.residuals
import pint.models.model_builder as mb
import pint.models.parameter as param
import pint.models.timing_model as tm
import pint.models

import astropy.units as u
import os

datadir = os.path.dirname(os.path.abspath(str(__file__)))
parfile = os.path.join(datadir, "NGC6440E.par")
timfile = os.path.join(datadir, "NGC6440E.tim")

# Define the timing model
m = mb.get_model(parfile)

# Read in the TOAs
t = pint.toa.get_TOAs(timfile)

# Print a summary of the TOAs that we have
t.print_summary()

# These are pre-fit residuals
rs = pint.residuals.Residuals(t, m).phase_resids
xt = t.get_mjds()

# Now do the fit
print("Fitting...")
f = pint.fitter.WLSFitter(t, m)
print(f.fit_toas())

print("\n Best model is:")
print(f.model.as_parfile())

# The following works
# add F2 to Spindown
p = param.prefixParameter(name="F2", value=0.0, 
                              units="Hz/s^2", 
                              type_match="Float", 
                              long_double=True)
m.add_param_from_top(p, "Spindown")
m.F2.frozen=False
m.components['Spindown'].setup()

# Now do the fit - should work
print("Fitting...")
f = pint.fitter.WLSFitter(t, m)
print(f.fit_toas())

# Now add a PhaseJump component and JUMP1 parameter
x = pint.models.jump.PhaseJump()
m.add_component(x, order=-1)
m.remove_param("JUMP1")
p = param.maskParameter(name="JUMP", index=1, key="MJD",
                        key_value=[53400, 53500], 
                        value=0.0, units='s')
m.add_param_from_top(p, "PhaseJump")
m.JUMP1.frozen=False

# This call registers the derivatives
m.components['PhaseJump'].setup()
# The following _parent setting happens in m.setup_components
# but we cannot run that more than once for some reason
# m.setup_components(m.components)
# This allows the subcomponent to access params from parent
m.components['PhaseJump']._parent = m

print(m.components)

print("Fitting...")
f = pint.fitter.WLSFitter(t, m)

print(f.fit_toas())
print(f.model.as_parfile())`
```

**Comment by luojing1211** [comment]
One has to run TimingModel.setup_component() to link the TimingModel to the ._parent attribute.

**Comment by scottransom** [comment]
@luojing1211   It seems like that linking could be done in the add_component() method for components that get added later.

**Comment by luojing1211** [comment]
Yes, It should be easy to add.
-Jing

**Comment by paulray** [comment]
I think this has been solved. Closing.
