### ISSUE TITLE
PINT should be able to output whitenened residuals

### ISSUE THREAD

**Issue by scottransom** [nanograv/PINT#602]
Given a red noise model, PINT should be able to output the whitened resids the same way that TEMPO does in the resid2.tmp  (print_resid does the subtraction of reddened and whitened residuals)

**Comment by demorest** [comment]
I will work on this, probably starting next week.  I'd originally thought it made sense for `GLSFitter` to output the noise realizations back to the relevant `NoiseComponent` classes in the timing/noise model.  However, since the noise realization depends on both a specific model and specific TOAs, I now think it makes more sense to add this to `Residuals`.  So `Residuals` will get some extra attributes that hold the noise realization for each noise component type after running a GLS fit.  Let me know if anyone sees any issues with this approach.

**Comment by demorest** [comment]
Addressed in #648
