### ISSUE TITLE
Cannot read white noise params from par files

### ISSUE THREAD

**Issue by tcromartie** [nanograv/PINT#620]
EFAC and EQUAD get applied fine when read from tim files, but if the parameters are listed in the par file, they're not applied. This might be a nice quality-of-life improvement (it's much easier to change them in the par file than in the tim file).

**Comment by luojing1211** [comment]
This is strange. I believe, if they are listed in the .par file, it should be applied. Can you check you model see if they are there?

**Comment by scottransom** [comment]
@luojing1211 I don't think so.  They are applied in .tim files during the TOA reading and EFAC and EQUAD change the TOA errors then.  But for it to get applied in the model, it would have to happen (I think) during computation of the residuals in the Residuals() class.  And that doesn't happen.

**Comment by paulray** [comment]
Yeah the Residuals class is probably the right place to do it, since that is when the model and TOAs get combined.  Another consequence of the modularity of models and TOAs in PINT.

**Comment by luojing1211** [comment]
Does this function do the job?
https://github.com/nanograv/PINT/blob/70e04c015ab0033e7db4e8ddbd4008c8b963b52e/src/pint/models/noise_model.py#L146

**Comment by scottransom** [comment]
@luojing1211 I'm not sure what job you are talking about.  It seems like it scales errors and stuff, but when/where is that used?  Especially in a WLS fit?  I see that it might be used in a GLS fit, but EFAC and EQUAD (at least) need to be used in both.

**Comment by luojing1211** [comment]
I meant to rescale the TOA errors. If you want to get rescaled TOA errors from .par file input, this function should return the result.  When we were designing WLS fitter, the noise model was not included. But the noise models were added when implementing the GLS fitter.  If WLS fitter also includes the noise model, what is the difference between WLS and GLS fitter? The red noise part?

**Comment by scottransom** [comment]
If there is a red noise model or ECORR, then you need to do a GLS fit.  But for a WLS fit, we have to be able to deal with EFAC and EQUAD.  Because those have been part of pulsar timing forever (and all types of WLS fits).  Luckily they only scale the TOA errors and so really only need to be applied in the residuals class.  They should affect the chi^2 value that the fitter evaluates.

So I think that the residuals class needs to check for EFAC and EQUAD, and if they exist, it needs to use them.  That should propagate directly to the WLS fitter, I think.  We need to be careful that the GLS fitter then doesn't apply things twice!

Also:  note that when EFAC and EQUAD are applied in the noise_model.py, I think you should use np.hypot() rather than sqrt with values squared inside.  That is bad for numerical precision.  See line 1535 in toa.py.

**Comment by luojing1211** [comment]
I this should be easy to fix. But we may face a challenge, an old challenge, if both tim file and par file has EFAC and EQUAD, it will apply those values in the .tim file but also apply the values in the .par file. Is there a priority for this case?

**Comment by scottransom** [comment]
Well, if they are in the .tim file they will have already have been applied.  So we should probably check when calling Residuals() to see if the TOAs have EFAC and EQUAD as well as the timing model, and if both do, we should probably give a warning at least.  I'm not sure we should exit, because I can see possible reasons why people would want to do that...

**Comment by luojing1211** [comment]
Ok, I think this could work.
