### ISSUE TITLE
START/FINISH parameters

### ISSUE THREAD

**Issue by vhaasteren** [nanograv/PINT#68]
In the parfiles, we can have START and FINISH parameters that prescribe the MJD range where we will fit for parameters. Although technically not 'parameters' of the timing model, they are read in from the parfile, so we should treat them as such and make them 'frozen'.

Several ideas on how to deal with them:
1) Ignore these parameters everywhere, except in the 'fitter' classes
2) Make a decorator for class methods of the TimingModel derivatives that 'slice' the toas astropy table that is passed to all the class methods of the timing model.
3) ...

I think it should be option (1), but let's discuss...

**Comment by paulray** [comment]
This is part of a more general question of how to handle parameters that control the behavior of the fitter, but aren't really part of the timing model (e.g. MODE, NITS), and parameters that are outputs from the fitter, rather than inputs to the fitter (e.g. TRES, NTOA, CHI2R).

Note that for START/FINISH, Tempo2 (at least, I'm not sure about TEMPO) have the strange behavior that they are ignored in the fitting process unless there is a "1" at the end of the line (as if indicating they are being fit for). In that case, all TOAs outside START--FINISH are ignored.  By default, Tempo2 writes its output par files with the "1".  This has caught me repeatedly as I extend my range of TOAs and can't figure out why they aren't being added to the fit!  I suggest we not adopt this default behavior.

None of this suggests which solution is best, but I just wanted to put those additional issues out there.

**Comment by vhaasteren** [comment]
Yes, good point, Paul.

I would say that output parameters from the fitter can be safely ignored, so we can make a list. Even tempo(2) ignores them.

As for the other parameters, they are in the parfile, so they need to be part of the model in 'some' way. Maybe we can add an attribute to parameters that makes them 'permanently frozen' or something like that. Or make it a subclass of Parameter, so we can enforce that behavior.

And you are right as well about START/FINISH, that behavior is odd. Even more odd is that their value changes internally during the fitting process, which I had to take counter measures for in the Qtip gui. Agreed that we should not necessarily adopt all the tempo(2) standard behavior, since some of it is just awkward.

**Comment by demorest** [comment]
FWIW, the convention of using a '1' flag on START/FINISH in the input
parfile to mean "ignore TOAs before/after this date" has been standard in
tempo for a long time.  Defaulting to writing out parfiles with the flag
set is not standard, and actually sounds like a bug to me.   In tempo, if
the '1' is used in the input, it is also present in the output, but
otherwise not.

**Comment by paulray** [comment]
As discussed at the telecon today, I created a [wiki page](https://github.com/nanograv/PINT/wiki/Discussion-of-Control-Parameters) where we can organize our thoughts on how to handle these types of parameters. Please edit the page with any thoughts or discussions!  Especially, make changes if you disagree with any of my initial characterizations.

**Comment by aarchiba** [comment]
I'd like to note that all of these are now ignored and not warned about. Perhaps if different handling is wanted there should be a new bug, and this one can be closed?

**Comment by swiggumj** [comment]
@luojing1211 @paulray Echoing @aarchiba's comment from almost a year ago... Can this issue be closed?

And maybe the control parameter wiki page can be revived with respect to more recent issues (e.g. https://github.com/nanograv/PINT/issues/748) and somehow distilled/incorporated in the docs -- if it hasn't already been.

**Comment by paulray** [comment]
Yes, this can be closed. A related issue is #635. I just asked @champagne-cmd to take a look at that one so at least after you do a fit the START and FINISH would track the first and last TOA and get written into the par file.
