### ISSUE TITLE
Weighted mean of post-fit residuals is not using scaled uncertainties; affecting chi2 calculation.

### ISSUE THREAD

**Issue by pennucci** [nanograv/PINT#810]
When I calculated the weighted mean of post-fit residuals it is ~identically zero when **not** applying EFAC/EQUADs, but presumably these factors should be used when fitting the mean phase, and thus the weighted mean should be zero when using the scaled TOA uncertainties as weights.  I found this using WidebandTOAFitter, but I tried with GLSFitter and it's the same, so I think it's a general issue.  This also affects the chi-squared calculation, since it uses the post-fit residuals; while the chi-squared calculation doesn't require zero-mean, I think this is implied in any set of post-fit timing residuals.

**Comment by demorest** [comment]
For GLS fits it's slightly more complicated.  chi2 requires the full noise model not just residuals and uncertainties (either scaled or not).  This is returned by the fitter, and I think it's best to use that value rather than duplicating the calculation elsewhere.  This means at least for chi2 purposes it doesn't matter where the zero-point of the residuals is.

**Comment by aarchiba** [comment]
This is indeed a bug where mean subtraction (when using a weighted mean) uses `get_errors` and not `get_data_error`. Fixed as part of a PR I'm working on, which should make mean subtraction/whitened residuals more readily available and consistent.
