### ISSUE TITLE
make_fake_toas does not attempt to produce zero residuals

### ISSUE THREAD

**Issue by aarchiba** [nanograv/PINT#821]
The function make_fake_toas claims to produce TOAs with zero residuals relative to a model; it makes no attempt to do this. The model is not used in any way.

**Comment by paulray** [comment]
Hmm, I had never heard of that function. We have a script `zima.py` that makes fake TOAs, but that does not use this function. This looks like something that @clp3ef probably added as part of her random models work.  If this function does become a good way to make TOAs with zero residual, then zima should be made to use it.

**Comment by clp3ef** [comment]
Hi Paul,

I did add that as part of the random models. Scott and I copied part of the
zima code over and modified it so it would produce evenly spaced TOAs with
zero residuals and no errors for the random model lines to be plotted with.
If making TOAs with zero residuals and zero errors is widely useful, our
modifications could probably be re-integrated into zima's code, but I don't
think zima should call make_fake_toas since it is just a modified copy of a
section of zima code and that seems messy and unnecessarily roundabout.

Camryn

**Comment by scottransom** [comment]
Yeah, Camryn needed this for her stuff.  And the goal (from me) was to pull this big out of zima and into a function that other code could use programmatically.  And zima could use it as well -- but we didn't get to that (yet?).

**Comment by paulray** [comment]
I see.  We should definitely try to work things out to avoid code duplication.

But Anne says make_fake_toas doesn't work?  I haven't looked at it yet.

**Comment by aarchiba** [comment]
Fixed in #814
