### ISSUE TITLE
Test_erfa failure on CI tests

### ISSUE THREAD

**Issue by luojing1211** [nanograv/PINT#836]
Currently, all of our branches' CI tests are failing due to the erfa test failing. It fails on the IERS -B tale download test. I remember there was a discussion about this in one of the telecons. When the IERS-B table gets updated, this will happen. Is there a nice way to avoid this?

**Comment by paulray** [comment]
I think the assumption in the test must not be true. It is checking that the downloaded version of IERS B is at least as current as the one that came shipped with astropy. For some reason, this is not true very soon after astropy is updated. This error will go away in a few days, but probably we should adjust the test a bit so that the downloaded version can be ~2 weeks or so out of date wrt the astropy one.

**Comment by aarchiba** [comment]
What is this test actually supposed to verify? It does not appear to call any PINT function. Is there any reason to include it? git blame says I originally created the test but that you (@paulray ) changed it to the current check-if-up-to-date?
