### ISSUE TITLE
Setting free_params does not fail as it should

### ISSUE THREAD

**Issue by pennucci** [nanograv/PINT#868]
`model = get_model(parfile);
model.free_params = ['garbage_parameter']`,
does not fail with `ValueError: garbage_parameter is not recognized as a parameter or alias` as I think it should (parfile doesn't have H4),
and
`model = get_model(parfile);
model.free_params = ['H4']`,
does not fail with `Parameter(s) are familiar but not in the model: H4` as I think it should,
and, perhaps worst of all,
`model = get_model(parfile);
model.free_params = ['DMJUMP']`
does not fail at all!  It should fail in the same way as the first example, but the silence over the subtle typo (the parameter should be `DMJUMP1` or `DMJUMP2`, etc.) leaves the user none the wiser!

**Comment by aarchiba** [comment]
I thought https://github.com/nanograv/PINT/blob/master/tests/test_timing_model.py#L179 would check this. I'll add some tests and start hunting.

**Comment by aarchiba** [comment]
Er, can you be a little more detailed about these? I can replicate the DMJUMP non-error, but I see ValueErrors for each of the other two. Perhaps a parfile and example code? Or backtraces if they fail but with the wrong exception?

The DMJUMP error is  because the parfile parsing process requires DMJUMP to be added as an alias for DMJUMP1. That code is extremely hard to understand - I rewrote it as get_model_new but that never replaced get_model - and so I'm having trouble figuring out how to fix the problem.

**Comment by aarchiba** [comment]
If you're concerned about unhelpful messages from the other two I can make subclasses of ValueError and do some more specific testing.

**Comment by pennucci** [comment]
Indeed, I get ValueErrors for the other two, but if I read the code correctly, the ValueError raised should reference the parameter (or parameters) that the user input to set free.  The ValueError I got in both was "ValueError: TNRedC is not recognized as a parameter or alias."  Not only is there _not_ a TNRedC in the model, but that's not the input.  And in the second case (if I read the code correctly, maybe I didn't), the ValueError should say H4 is recognized but is not in the model.

**Comment by pennucci** [comment]
FWIW, I know that TNRedC is tempo2 speak for the number of red 'timing' noise Fourier components (I think), and red noise _is_ part of the model -- so I'm not sure what to make of that either.  Why should that be unrecognized?  Why should it show up in this error message? etc.

**Comment by aarchiba** [comment]
The wrong parameter name was a bug. (Now tested and fixed in the PR.) 

I'm less clear about H4 - I'm not familiar with that parameter or with the binary model that includes it (ELL1H?).  But if you had a model that included F0 and F1, I'm not actually sure what should happen if you tried to set F2 as a free parameter. Probably you should have to add it by hand?

I'm not sure that second ValueError will ever trigger - I think the alias matching is done on the parameters the model actually has, which is the same set that are possibly free/frozen. I could make the message more alarming, but I don't want to remove the check in case that internal invariant (how `match_parameter_aliases`) changes.

**Comment by pennucci** [comment]
Yeah, it's in ELL1H.  If the second one doesn't trigger, that's OK.  It's a minor issue; but good that the other bug was fixed; thanks!
