### ISSUE TITLE
Fix badges

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#929]
In README.rst, the build, docs and coverage badges are tied to travis-ci. Now that we have removed that and are using GitHub actions, we need to fix that.  Any ideas @matteobachetti ?

**Comment by paulray** [comment]
OK, I fixed the build badges! We need to figure out how to get the coverage badge to be active now, and why the docs badge shows failing.

**Comment by matteobachetti** [comment]
For the docs, you should check the readthedocs admin page for build errors. For coverage, at the end of the Actions build there is a message "No coverage data found", I think I've seen that before and I need to look it up

**Comment by paulray** [comment]
OK, the docs build is failing because some of the notebooks are taking too much time/memory to execute and are crashing the build:
https://readthedocs.org/projects/nanograv-pint/builds/12631935/

@luojing1211 @aarchiba did some of the notebooks get a lot more complicated recently?

**Comment by luojing1211** [comment]
The last two example in the doc building, compare_B1855_tempo2 is script that runs tempo2 instead of a notebook. This may be the reason that uses a lot of memory.

**Comment by aarchiba** [comment]
The conversion of our example notebooks to `.py` files has confused Sphinx somewhat, as it now thinks all our `.py` files in the examples directory are potentially Sphinx source files. Normally they are not executed because they aren't included anywhere in the docs, and in local builds they aren't, but it seems like something different might be happening on the docs build? It was working fine on that PR when it went in.

**Comment by paulray** [comment]
It looks like the docs badge is fixed. All we need now is to fix up the coverage report/badges.
