### ISSUE TITLE
Strange behavior from Fitter

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#958]
In this example, I take the 15yr solution for J0740+6620 and freeze all the FD parameters at 0.0.  I then fit the solution and then iterate adding one FD parameter at a time and refitting.  Each time you add a parameter, the chi2 should decrease. It does this for each parameter addition until after the first fit that includes FD5, the chi2 is 13584.93.  The problem is that a second iteration of the fitter with no further changes to the free parameters makes ch2 jump up to 13585.40, then another iteration makes it jump to 13585.41, at which point it stabilizes around that value with further iterations. No minimum chi2 fitter should find a higher value on a second iteration, right? 

So, there are two components to this issue:
(1) Running a fitter iteration should never increase chi2 since the parameter values that give the lower chi2 are still valid and could be kept.
(2) Calling `fit_toas()` should probably return a converged fit by default, unless the user really knows that they want to only run one iteration and possibly get an unconverged fit.

Is any of this behavior due to GLSFitter instead of WLSFitter?  I haven't tried that yet.

![Screen Shot 2021-01-22 at 9 12 22 AM](https://user-images.githubusercontent.com/1771428/105501362-1ad3c980-5c92-11eb-9f9b-20d81f617f35.png)
![Screen Shot 2021-01-22 at 9 12 41 AM](https://user-images.githubusercontent.com/1771428/105501368-1d362380-5c92-11eb-989e-5e21e1009986.png)

**Comment by paulray** [comment]
OK, this issue is not specific to GLSFitter. It happens with WLSFitter as well. Here again, when you free FD5, the chi2 goes up, then settles down a bit lower with more iterations but never gets as low as it was with FD4. Something is definitely funky. I'm pretty sure it is related to the huge covariance between the FD params and DMX.


![Screen Shot 2021-01-22 at 12 42 50 PM](https://user-images.githubusercontent.com/1771428/105525692-6d6fae80-5caf-11eb-8bfc-e22c0a4987dd.png)

**Comment by aarchiba** [comment]
As a short-term solution, one could add a parameter that would tell `fit_toas` to stop if the chi-squared didn't improve by at least that much; then one could run with a larger `maxiter` by default.

As a longer-term solution, we're going to need to come up with a better fitting procedure than just "pretend it's linear and do one step". The most direct solution would be to use `scipy.optimize.least_squares`, which also supports parameter bounds, but I am a little concerned that it doesn't support `long double`. Since we are usually close enough to convergence to work in a step or two, we might be able to get away with just a few of the ideas from a proper algorithm.

**Comment by aarchiba** [comment]
Could you try this with `DownhillWLSFitter` and/or `DownhillGLSFitter` from PR #975? I *think* it should fix this, though if the problem is degeneracy it might just complain that it's stuck. Adjusting `threshold` might or might not help by tweaking the SVD handling.
