### ISSUE TITLE
pintk prefit residuals don't work right

### ISSUE THREAD

**Issue by paulray** [nanograv/PINT#973]
If I go in the examples directory and run this command:
```
pintk NGC6440E.par NGC6440E.tim
```
When I start the prefit and postfit resids are the same, which is fine since I have not done a fit.
The problem is that if I click "Refit" it fits the data and the postfit residuals flatten out, but when I click back to the prefit resids, they are the same as the post-fit. The prefit resids should be the resids from just before the last time  a fit was run.

**Comment by champagne-cmd** [comment]
Just to clarify: the prefit residuals should be constant the entire pintk session? Right now it appears they are updated so that prefit is the value before the current iteration rather than the initial value (so they are pre-current fit rather than pre-any fit). Of course, if you just immediately fit again without changing anything, now the prefit and postfit are equal, so another option would be to check that the fit actually did something and only update prefit then. Which implementation is correct?

**Comment by paulray** [comment]
I think the usual definition of prefit is just before the current iteration of the fit. So if you start and just click "Fit" one time, you should have the original resids as "Prefit"" and the new residuals as "Postfit".  I just tried this with the NGC6440E example and before clicking Fit, both prefit and postfit show the big sine wave residuals.  After clicking Fit, both show flat residuals, when Prefit should still show the big sine wave.

**Comment by aarchiba** [comment]
@paulray Can you confirm that the merged PR fixes this bug and close if appropriate?

**Comment by paulray** [comment]
Confirmed. This is fixed.
